//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleCMS.LocalResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleCMS.LocalResources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 全部文章 的本地化字符串。
        /// </summary>
        public static string AllArticle {
            get {
                return ResourceManager.GetString("AllArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该输入项只能包含半角字母,数字和_ 的本地化字符串。
        /// </summary>
        public static string AlphanumText {
            get {
                return ResourceManager.GetString("AlphanumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该输入项只能包含半角字母和_ 的本地化字符串。
        /// </summary>
        public static string AlphaText {
            get {
                return ResourceManager.GetString("AlphaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音频 的本地化字符串。
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文章类别 的本地化字符串。
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文章类别 的本地化字符串。
        /// </summary>
        public static string CategoryArticle {
            get {
                return ResourceManager.GetString("CategoryArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容 的本地化字符串。
        /// </summary>
        public static string CategoryContent {
            get {
                return ResourceManager.GetString("CategoryContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 题图 的本地化字符串。
        /// </summary>
        public static string CategoryImage {
            get {
                return ResourceManager.GetString("CategoryImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父类别 的本地化字符串。
        /// </summary>
        public static string CategoryParentId {
            get {
                return ResourceManager.GetString("CategoryParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序序数 的本地化字符串。
        /// </summary>
        public static string CategorySortOrder {
            get {
                return ResourceManager.GetString("CategorySortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string CategoryState {
            get {
                return ResourceManager.GetString("CategoryState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        public static string CategoryTitle {
            get {
                return ResourceManager.GetString("CategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要更改的字段不存在 的本地化字符串。
        /// </summary>
        public static string CheckChangeFieldNoExist {
            get {
                return ResourceManager.GetString("CheckChangeFieldNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 与 {1} 的值不匹配 的本地化字符串。
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认密码 的本地化字符串。
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文章 的本地化字符串。
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容 的本地化字符串。
        /// </summary>
        public static string ContentBody {
            get {
                return ResourceManager.GetString("ContentBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类别编号 的本地化字符串。
        /// </summary>
        public static string ContentCategoryId {
            get {
                return ResourceManager.GetString("ContentCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建日期 的本地化字符串。
        /// </summary>
        public static string ContentCreated {
            get {
                return ResourceManager.GetString("ContentCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击量 的本地化字符串。
        /// </summary>
        public static string ContentHits {
            get {
                return ResourceManager.GetString("ContentHits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 题图 的本地化字符串。
        /// </summary>
        public static string ContentImage {
            get {
                return ResourceManager.GetString("ContentImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序序数 的本地化字符串。
        /// </summary>
        public static string ContentSortOrder {
            get {
                return ResourceManager.GetString("ContentSortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string ContentState {
            get {
                return ResourceManager.GetString("ContentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 摘要 的本地化字符串。
        /// </summary>
        public static string ContentSummary {
            get {
                return ResourceManager.GetString("ContentSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签 的本地化字符串。
        /// </summary>
        public static string ContentTags {
            get {
                return ResourceManager.GetString("ContentTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        public static string ContentTitle {
            get {
                return ResourceManager.GetString("ContentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyyy-MM-dd 的本地化字符串。
        /// </summary>
        public static string DefaultDateFormat {
            get {
                return ResourceManager.GetString("DefaultDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyyy-MM-dd HH:mm:ss 的本地化字符串。
        /// </summary>
        public static string DefaultDatetimeFormat {
            get {
                return ResourceManager.GetString("DefaultDatetimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  {0} {1} 已删除 的本地化字符串。
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有找到要删除的记录 的本地化字符串。
        /// </summary>
        public static string DeletedNotExist {
            get {
                return ResourceManager.GetString("DeletedNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该输入项必须是电子邮件地址，格式如： &quot;user@example.com&quot; 的本地化字符串。
        /// </summary>
        public static string EmailText {
            get {
                return ResourceManager.GetString("EmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} “{1}”已存在 的本地化字符串。
        /// </summary>
        public static string Exists {
            get {
                return ResourceManager.GetString("Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件大小超出限制范围 的本地化字符串。
        /// </summary>
        public static string FileSizeNotAllow {
            get {
                return ResourceManager.GetString("FileSizeNotAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不允许的文件类型 的本地化字符串。
        /// </summary>
        public static string FileTypeNotAllow {
            get {
                return ResourceManager.GetString("FileTypeNotAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有访问权限 的本地化字符串。
        /// </summary>
        public static string Forbid403 {
            get {
                return ResourceManager.GetString("Forbid403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁止删除 {0}，因为有与之相关联的记录，请先删除与之关联的记录再删除 的本地化字符串。
        /// </summary>
        public static string ForbidDelete {
            get {
                return ResourceManager.GetString("ForbidDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 节点下还有子节点，不允许删除 的本地化字符串。
        /// </summary>
        public static string HasChild {
            get {
                return ResourceManager.GetString("HasChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片 的本地化字符串。
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器内部错误 的本地化字符串。
        /// </summary>
        public static string InternalServerError500 {
            get {
                return ResourceManager.GetString("InternalServerError500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入值非法 的本地化字符串。
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非法的类别 的本地化字符串。
        /// </summary>
        public static string InvalidCategoryId {
            get {
                return ResourceManager.GetString("InvalidCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 是无效的日期 - 必须符合格式： {1} 的本地化字符串。
        /// </summary>
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户已禁止登录 的本地化字符串。
        /// </summary>
        public static string IsApprove {
            get {
                return ResourceManager.GetString("IsApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取数据失败 的本地化字符串。
        /// </summary>
        public static string ListFailure {
            get {
                return ResourceManager.GetString("ListFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户已被锁定 的本地化字符串。
        /// </summary>
        public static string LockedOut {
            get {
                return ResourceManager.GetString("LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该输入项的最大值是 {0} 的本地化字符串。
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该输入项的日期必须在 {0} 之前 的本地化字符串。
        /// </summary>
        public static string MaxDate {
            get {
                return ResourceManager.GetString("MaxDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该输入项的最大长度是 {0} 个字符 的本地化字符串。
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 媒体 的本地化字符串。
        /// </summary>
        public static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        public static string MediaDescription {
            get {
                return ResourceManager.GetString("MediaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名 的本地化字符串。
        /// </summary>
        public static string MediaFieldName {
            get {
                return ResourceManager.GetString("MediaFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径 的本地化字符串。
        /// </summary>
        public static string MediaPath {
            get {
                return ResourceManager.GetString("MediaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件大小 的本地化字符串。
        /// </summary>
        public static string MediaSize {
            get {
                return ResourceManager.GetString("MediaSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 媒体类型 的本地化字符串。
        /// </summary>
        public static string MediaType {
            get {
                return ResourceManager.GetString("MediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传日期 的本地化字符串。
        /// </summary>
        public static string MediaUploadedDate {
            get {
                return ResourceManager.GetString("MediaUploadedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该输入项的最小值是 {0} 的本地化字符串。
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该输入项的日期必须在 {0} 之前 的本地化字符串。
        /// </summary>
        public static string MinDate {
            get {
                return ResourceManager.GetString("MinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该输入项的最小长度是 {0} 个字符 的本地化字符串。
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 不是有效的手机号码 的本地化字符串。
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 不是有效数值 的本地化字符串。
        /// </summary>
        public static string Nan {
            get {
                return ResourceManager.GetString("Nan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码 的本地化字符串。
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有找到符合要求的排序信息 的本地化字符串。
        /// </summary>
        public static string NoAllowSortDefine {
            get {
                return ResourceManager.GetString("NoAllowSortDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未分类 的本地化字符串。
        /// </summary>
        public static string NoCategoryArticle {
            get {
                return ResourceManager.GetString("NoCategoryArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有上传任何文件 的本地化字符串。
        /// </summary>
        public static string NoFileUpload {
            get {
                return ResourceManager.GetString("NoFileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能将子节点设置为当前节点的父节点 的本地化字符串。
        /// </summary>
        public static string NotChildToParent {
            get {
                return ResourceManager.GetString("NotChildToParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有找到页面 的本地化字符串。
        /// </summary>
        public static string NotFound404 {
            get {
                return ResourceManager.GetString("NotFound404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不允许将节点自身作为自己的父节点 的本地化字符串。
        /// </summary>
        public static string NotSelfToParent {
            get {
                return ResourceManager.GetString("NotSelfToParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧密码 的本地化字符串。
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新密码不能与旧密码相同 的本地化字符串。
        /// </summary>
        public static string OldPasswordEqualNew {
            get {
                return ResourceManager.GetString("OldPasswordEqualNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发生错误 的本地化字符串。
        /// </summary>
        public static string OtherError {
            get {
                return ResourceManager.GetString("OtherError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码必须由字母和数字组成 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 两次输入的密码不同 的本地化字符串。
        /// </summary>
        public static string PasswordNoEqual {
            get {
                return ResourceManager.GetString("PasswordNoEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该输入项的值必须在 {0} 与 {1} 之间 的本地化字符串。
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要获取的信息不存在或已被删除 的本地化字符串。
        /// </summary>
        public static string RecordNoExist {
            get {
                return ResourceManager.GetString("RecordNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该输入项为必输项 的本地化字符串。
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色 的本地化字符串。
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误的用户名或密码 的本地化字符串。
        /// </summary>
        public static string SignInFailure {
            get {
                return ResourceManager.GetString("SignInFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签 的本地化字符串。
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签名称 的本地化字符串。
        /// </summary>
        public static string TagTagName {
            get {
                return ResourceManager.GetString("TagTagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要更新的 {0} 不存在或已被删除 的本地化字符串。
        /// </summary>
        public static string UpdatedNoExist {
            get {
                return ResourceManager.GetString("UpdatedNoExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该输入项必须是URL地址，格式如： &quot;http://www.example.com&quot; 的本地化字符串。
        /// </summary>
        public static string UrlText {
            get {
                return ResourceManager.GetString("UrlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有选择角色 的本地化字符串。
        /// </summary>
        public static string UserRoles {
            get {
                return ResourceManager.GetString("UserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string UserUserName {
            get {
                return ResourceManager.GetString("UserUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码错误 的本地化字符串。
        /// </summary>
        public static string VerifyCode {
            get {
                return ResourceManager.GetString("VerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频 的本地化字符串。
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
    }
}
